# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PITSubpopulations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tab', models.CharField(max_length=18)),
                ('Pop_Type', models.CharField(max_length=35)),
                ('Shelter', models.CharField(max_length=11)),
                ('Date', models.DateField()),
                ('Value', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
